### ISSUE TITLE
Use custom domain or all-contributors.js.org

### ISSUE THREAD

**Issue by jakebolam** [all-contributors/all-contributors#150]
## Motivation
`all-contributors.js.org` may put off projects using other languages, and all-contributors is intended for everyone!

Which domain should we use?

## Context
- .js.org has better SEO and trust in the community.
- there are already a bunch of links to all-contributors.js.org on the internet, we would need to support redirects
- we own cnames `all-contributors.js.org`, `allcontributors.com`, `allcontributors.org`, `all-contributors.com`, `all-contributors.org`

## Work in-progress
- [ ] Update app and marketplace
- [ ] Update probot listing direct
- [ ] Update CLI
- [ ] Update bot
- [ ] Enable redirect, retire old pages

**Comment by dance2die** [comment]
I 👍 `allcontributors.com`.

1. Domains without non-ascii characters look more authentic IMHO.
1. I find it easier to type

`.js.org` might be SEO friendly but haven't seen many `.js.org` sites popup in my Google results.

**Comment by tbenning** [comment]
I think the most ideal would be allcontributors.org. It seems quite common for open source projects to use .org. 

Using allcontributors.com is good too, but might seem like more of a tech company rather than an open source tool/community.

Examples: 
https://reactjs.org/
https://www.gatsbyjs.org/

**Comment by Berkmann18** [comment]
`.js.org` is not a TLD I've seen much (if not at all) so I doubt it would be easy to remember when looking for the website, it also seems longer than needed.
`.com` as @tbenning pointed out make the `allcontributors` name seem like a corporation/company instead of an `org`anisation (which is what `.org` is for).

So I'll prefer having `allcontributors.org` over the other two.

Regarding the SEO, the domain name is just a portion of it and if there's a redirection from the current one to the new one or/and if the referee pages (ie those who points to the website) updates the URL then it won't affect it at all.

**Comment by jakebolam** [comment]
Thanks for the input everyone! Plan is to roll this out today!

**Comment by jakebolam** [comment]
Update: rollout is blocked, waiting on DNS name server propagation. ~30 hours into the 48 hour window.
