### ISSUE TITLE
Logo Suggestion

### ISSUE THREAD

**Issue by Thatkookooguy** [all-contributors/all-contributors#224]
Hello, all-contributors maintainers :-)

I took a look at your logo in your documentation and bot and felt like it was missing something.
Also, it had some rough edges which bothered me (like a color transparency leftovers).

I created a new logo which I thought might suit better.

Here it is:
https://codepen.io/neilkalman/full/jJqQMo

And in png form:
<img width="552" alt="logo-all" src="https://user-images.githubusercontent.com/10427304/53689482-bb980380-3d5f-11e9-9868-3bf377101c53.png">
<img width="188" alt="logo-transparent" src="https://user-images.githubusercontent.com/10427304/53689483-c05cb780-3d5f-11e9-8957-4031290ba9a1.png">

I think it relates better to what this project does, which is create a table of **squares** of all the **people** who contributed to the project. I tried to implement that into the logo. Also, the misalignment of the squares represents new people joining in.

The male face is taken from [the material icons project](https://material.io/tools/icons/?icon=face&style=baseline) and the girl's face is taken from [wikimedia commons](https://commons.wikimedia.org/wiki/File:Ic_face_unlock_48px.svg). Both should have the right usage rights

**Comment by Thatkookooguy** [comment]
I can create all the versions needed if you decide to go with this (svg, x2, x4, favicon, etc)

**Comment by MatheusRV** [comment]
I prefer atual, but icon is nice.

**Comment by Thatkookooguy** [comment]
@MatheusRV what is atual?

**Comment by tbenning** [comment]
First of all, thanks for the suggestion! We always welcome ideas. I'm the original designer of the current logo. 

I too had noticed some of the pixelation in the current implementation. We're going to replace those assets ASAP. @Thatkookooguy Can you help show screenshots of the pixelation that you're seeing on your end? That will help us out a ton!

A few things about the suggestion:
-Unsure if it will work at small sizes with the complex shapes
-The current logo pays homage to the "stars" emoji that @kentcdodds has been using on the project since its inception. We chose to reuse it in the ideogram to continue to tie the brand to its origins. We've prioritized legibility with the the typography we chose. We had looked at other iterations, and this one stood out to the maintainers I showed it to.

Again, thanks for the suggestion and feedback, but I think we're going to keep the logo, since we just changed it a month or so ago, and aren't looking to rebrand or confuse users with a new logo!

**Comment by Thatkookooguy** [comment]
@tbenning sure! The logo was just a suggestion so I totally understand. especially if you changed to that logo just a month ago!

Added screenshots and where I found the pictures in the description below.

Basically, I wanted to take the logo and use it in our "technologies" page for one of [kibibit](https://github.com/kibibit)'s projects

So I tried opening the logo both from the homepage and the docs

- Home page logo in the wild looks great since it's on a white background:
![screen shot 2019-03-04 at 3 22 04 pm](https://user-images.githubusercontent.com/10427304/53736047-55130280-3e91-11e9-811f-51da8d237bc5.png)
But when opening the image in a new tab, you could see the white around it (looks like it got fixed now!)

- In the documentation, the logo have the same behaviour, where on white background it looks great.

That logo **is still pixelated on the edges**:
https://allcontributors.org/docs/assets/logo-full-transparent.png
![screen shot 2019-03-04 at 3 24 54 pm](https://user-images.githubusercontent.com/10427304/53736184-ae7b3180-3e91-11e9-8369-8f631d373a46.png)

**Comment by Thatkookooguy** [comment]
oh here's the other one: https://d33wubrfki0l68.cloudfront.net/d630d4b9660d8e047e6ef219f3d2db7c61683769/6a90e/img/icons/logo-square-transparent.png
