### ISSUE TITLE
Put table into website

### ISSUE THREAD

**Issue by Cool-Scratcher** [all-contributors/all-contributors#469]
The documentation is not clear. How do you insert a table of contributors into a website?

**Comment by Berkmann18** [comment]
Have you gone through the configuration and set the file where the table will be added?

**Comment by Cool-Scratcher** [comment]
> Have you gone through the configuration and set the file where the table will be added?

No... where in the docs does it say to do that?

**Comment by Berkmann18** [comment]
> No... where in the docs does it say to do that?

CLI: https://allcontributors.org/docs/en/cli/configuration
Bot: https://allcontributors.org/docs/en/bot/configuration

**Comment by Cool-Scratcher** [comment]
> > No... where in the docs does it say to do that?
> 
> CLI: https://allcontributors.org/docs/en/cli/configuration
> Bot: https://allcontributors.org/docs/en/bot/configuration

The docs aren't very clear.
I used the bot for my GitHub repo, but I don't know how to use the CLI.

**Comment by Berkmann18** [comment]
@Cool-Scratcher Can you please elaborate.
Have you used CLIs before?

**Comment by cope** [comment]
@Berkmann18 You don't seem to understand his question.

@Cool-Scratcher followed all the defined steps and yet does not see the table of contributors.

And I am here because I have the same problem.

- I installed the bot
- I configured the bot by adding the .all-contributorsrc
- I created a pull request and commented on it with `@all-contributors please add...`
- The bot created a merge request to add the contributor
- I merged and the contributor is now listed in [.all-contributorsrc](https://github.com/owservable/owservable/blob/main/.all-contributorsrc)

But is still **NOT** showing in the [README](https://github.com/owservable/owservable).

What is missing?

**Comment by cope** [comment]
ping

**Comment by cope** [comment]
@Cool-Scratcher 

The documentation is missing that you need to add this to your README:

```
# Contributors

<!-- ALL-CONTRIBUTORS-LIST:START - Do not remove or modify this section -->
<!-- prettier-ignore-start -->
<!-- markdownlint-disable -->



<!-- markdownlint-restore -->
<!-- prettier-ignore-end -->
<!-- ALL-CONTRIBUTORS-LIST:END -->

```

I think you can (or should) also add some initial HTML table, but I am still trying to figure this out further.

**Comment by Berkmann18** [comment]
@cope I can see why it's not clear when the only part that mentions it is https://allcontributors.org/docs/en/cli/usage, feel free to suggest a better way to address this.

**Comment by tenshiAMD** [comment]
@cope @Cool-Scratcher Please check the [installation guide](https://allcontributors.org/docs/en/bot/installation#3-create-a-readmemd) again. Thanks! 🎉
